services:
  backend:
    build:
      context: .
      target: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
  database:
    build:
      context: .
      target: database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    volumes:
      - ceet_db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
  web:
    depends_on:
      - backend
    build:
      context: .
      target: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80

volumes:
  ceet_db:
