services:
  backend:
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=postgres://postgres:ceetdb@database/postgres
    ports:
      - "3000:3000"
  database:
    environment:
      - POSTGRES_PASSWORD=ceetdb
    healthcheck:
      interval: 1s
      test: 'pg_isready --username=postgres'
    image: postgres
    volumes:
      - ceet_db:/var/lib/postgresql/data

volumes:
  ceet_db:
