services:
  database:
    build:
      context: .
      target: database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "--username=postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ceet_db:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

  backend:
    build:
      context: .
      target: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGURI=${PGURI}
    ports:
      - "3000:3000"

  web:
    build:
      context: .
      target: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

volumes:
  ceet_db:
